install:
	./scripts/yay
	./scripts/base
	./scripts/home
	./scripts/zsh
	./scripts/php
	./scripts/tmux
	./scripts/nvim
	./scripts/gui
	./scripts/audio
	./scripts/kitty
	./scripts/composer
	./scripts/browsers
	./scripts/slack
	./scripts/spotify
	./scripts/insomnia
