#!/usr/bin/sh

yay -S --noconfirm neovim vim-ruby vim-plug

# Python support for vim
pip install neovim
pip2 install neovim

mkdir -p /home/antoine/.config/nvim/

ln -s -f /home/antoine/.dotfiles/nvim/init.vim /home/antoine/.config/nvim/init.vim
ln -s -f /home/antoine/.dotfiles/nvim/colors /home/antoine/.config/nvim/colors

nvim +'PlugInstall --sync' +qa
