#!/usr/bin/sh

yay -S --noconfirm neovim vim-plug xsel

# Python support for vim
pip install neovim

rm -rf /home/antoine/.config/nvim
cp -rf /home/antoine/.dotfiles/nvim/config /home/antoine/.config/nvim

nvim +'PlugInstall --sync' +qa
