#!/bin/sh

yay -S --noconfirm \
    git \
    openssh \
    wget \
    man-db \
    zip \
    unzip \
    exa \
    fd \
    ripgrep \
    xclip \
    diff-so-fancy \
    keychain \
    neofetch

mkdir -p /home/$(whoami)/.config

ln -sf $(git rev-parse --show-toplevel)/.gitconfig $HOME/.gitconfig
ln -sf $(git rev-parse --show-toplevel)/.gitignore $HOME/.gitignore
ln -sf $(git rev-parse --show-toplevel)/.ssh/config $HOME/.ssh/config
