#!/bin/sh

yay -S --noconfirm bspwm sxhkd rofi xinit thunar

ln -sf $(git rev-parse --show-toplevel)/.config/bspwm $HOME/.config/bspwm
ln -sf $(git rev-parse --show-toplevel)/.config/sxhkd $HOME/.config/sxhkd
ln -sf $(git rev-parse --show-toplevel)/.config/rofi $HOME/.config/rofi
ln -sf $(git rev-parse --show-toplevel)/.xinitrc $HOME/.xinitrc
