#!/bin/sh

yay -S --noconfirm xorg-server xf86-video-intel bspwm sxhkd rofi jq polybar xorg-xinit xorg-xsetroot picom thunar la-capitaine-icon-theme nerd-fonts-fira-code otf-font-awesome ttf-dejavu ttf-material-icons

ln -sf $(git rev-parse --show-toplevel)/.config/bspwm $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/sxhkd $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/rofi $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/polybar $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.xinitrc $HOME/.xinitrc
ln -sf $(git rev-parse --show-toplevel)/.xprofile $HOME/.xprofile
ln -sf $(git rev-parse --show-toplevel)/.Xresources $HOME/.Xresources

ln -sf $(git rev-parse --show-toplevel)/etc/X11/xorg.conf.d/00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
