#!/bin/sh

(cd $HOME && mkdir Projects Images Videos Documents Downloads .bin)

ln -sf $(git rev-parse --show-toplevel)/.bin/askpass-rofi $HOME/.bin/askpass-rofi
ln -sf $(git rev-parse --show-toplevel)/.bin/dood $HOME/.bin/dood
ln -sf $(git rev-parse --show-toplevel)/.bin/lock $HOME/.bin/lock
cp -r $(git rev-parse --show-toplevel)/home/* $HOME
