#!/bin/sh

yay -S --needed --noconfirm tmux alacritty

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -sf $(git rev-parse --show-toplevel)/.tmux.conf $HOME/.tmux.conf
ln -sf $(git rev-parse --show-toplevel)/.config/tmux $HOME/.config
ln -sf $(git rev-parse --show-toplevel)/.config/alacritty $HOME/.config
