#!/bin/sh

yay -S --needed --noconfirm zsh zplug zsh-theme-powerlevel9k-git

ln -sf $(git rev-parse --show-toplevel)/.zshrc $HOME/.zshrc

zsh -c 'source ~/.zshrc && zplug install'

chsh -s /usr/bin/zsh
